# Generated by Django 4.1.13 on 2026-03-23 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblCRMAcciones',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblCRMContactos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=80, null=True)),
                ('PrimerApellido', models.CharField(max_length=80, null=True)),
                ('SegundoApellido', models.CharField(max_length=80, null=True)),
                ('FechaCumple', models.DateField(null=True)),
                ('Direccion', models.CharField(max_length=20, null=True)),
                ('Numero', models.CharField(max_length=20, null=True)),
                ('Colonia', models.CharField(max_length=20, null=True)),
                ('Localidad', models.CharField(max_length=20, null=True)),
                ('Municipio', models.CharField(max_length=20, null=True)),
                ('Estado', models.CharField(max_length=20, null=True)),
                ('Pais', models.CharField(max_length=20, null=True)),
                ('CP', models.IntegerField(null=True)),
                ('Referencia', models.CharField(max_length=50, null=True)),
                ('NoCelular', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=60, null=True)),
                ('TelOficina', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblCRMEstadoOportu',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NomCorto', models.CharField(max_length=30, null=True)),
                ('Descripcion', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblCRMListaProdInteres',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tblCRMRutas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NomCorto', models.CharField(max_length=30, null=True)),
                ('Descripcion', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblCRMTipoContacto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NomCorto', models.CharField(max_length=30, null=True)),
                ('Descripcion', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblCRMVendedores',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NomCorto', models.CharField(max_length=80, null=True)),
                ('Nombre', models.CharField(max_length=80, null=True)),
                ('Apellidos', models.CharField(max_length=80, null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('Celular', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tblanimalestipo',
            name='Descripcion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblasignacorrales',
            name='Fecha',
            field=models.DateTimeField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblclientes',
            name='Ciudad',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblclientes',
            name='Contacto',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblclientes',
            name='Direccion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblclientes',
            name='Nombre',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tblclientes',
            name='TelefonoContacto',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblcontenedoresmateriaprima',
            name='Capacidad',
            field=models.FloatField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblcontenedoresmateriaprima',
            name='Cliente',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblcontenedoresproductos',
            name='Capacidad',
            field=models.FloatField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblcontenedoresproductos',
            name='Proveedor',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblcorrales',
            name='Clave',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblcorrales',
            name='Descripcion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblcorrales',
            name='FechaAsigna',
            field=models.DateTimeField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tbldetallemovanimales',
            name='IDFolio',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tblentradamp',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblentradamp',
            name='notas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblentradaproductos',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblestatus',
            name='Descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblinventarioinicialesmp',
            name='Fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblinventarioinicialesproductos',
            name='Fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblmateriaprima',
            name='Descripcion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblmovimientoanimales',
            name='Notas',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='tbloperadores',
            name='Descripcion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblotrosdatosmovmp',
            name='Camion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblotrosdatosmovmp',
            name='Chofer',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblotrosdatosmovmp',
            name='Placas',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblotrosdatossalxbas',
            name='Camion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblotrosdatossalxbas',
            name='Chofer',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblotrosdatossalxbas',
            name='Placas',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblproductos',
            name='Descripcion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblproveedores',
            name='Ciudad',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblproveedores',
            name='Contacto',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblproveedores',
            name='Direccion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblproveedores',
            name='Nombre',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tblproveedores',
            name='TelefonoContacto',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblsalidamp',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblsalidaproductos',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblservido',
            name='Fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblservido',
            name='FechaAServir',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tblservido',
            name='FechaServida',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tbltecnicos',
            name='AreaRegistro',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tbltecnicos',
            name='IDFila',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbltecnicos',
            name='IDFilaTabla',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbltecnicos',
            name='NombreTabla',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tbltecnicos',
            name='Tecnico',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tbltecnicos',
            name='TecnicoEditor',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tbltecnicos',
            name='TecnicoElimino',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tbltipomaterial',
            name='Descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbltipomov',
            name='Descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbltipopresentacion',
            name='Descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbltolva',
            name='Alias',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tbltolva',
            name='Modelo',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tblunidades',
            name='Abreviacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblunidades',
            name='Descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='tblCRMOportunidades',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreProyecto', models.CharField(max_length=120, null=True)),
                ('MontoOpo', models.IntegerField(null=True)),
                ('FechaCierreEstim', models.DateField(null=True)),
                ('FechaDeCierre', models.DateField(null=True)),
                ('IDContacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcrmcontactos')),
                ('IDEstadoVenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcrmestadooportu')),
                ('IDListaProdsInteres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcrmlistaprodinteres')),
                ('IDVendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcrmvendedores')),
            ],
        ),
        migrations.AddField(
            model_name='tblcrmlistaprodinteres',
            name='IDProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproductos'),
        ),
        migrations.AddField(
            model_name='tblcrmcontactos',
            name='IDCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblclientes'),
        ),
        migrations.AddField(
            model_name='tblcrmcontactos',
            name='IDRuta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcrmrutas'),
        ),
        migrations.AddField(
            model_name='tblcrmcontactos',
            name='IDTipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcrmtipocontacto'),
        ),
        migrations.CreateModel(
            name='tblCRMBitacoraInteracciones',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Notas', models.CharField(max_length=120, null=True)),
                ('FechaInterac', models.DateField(null=True)),
                ('FechaProxSegui', models.DateField(null=True)),
                ('IDOportunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcrmoportunidades')),
                ('IDTipoAccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcrmacciones')),
            ],
        ),
    ]
