# Generated by Django 4.1.13 on 2026-03-23 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_tblcrmacciones_tblcrmcontactos_tblcrmestadooportu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcrmoportunidades',
            name='IDListaProdsInteres',
        ),
        migrations.AddField(
            model_name='tblcrmoportunidades',
            name='IDProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproductos'),
        ),
    ]
