# Generated by Django 4.1.13 on 2026-03-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_remove_tblcrmoportunidades_idlistaprodsinteres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcrmbitacorainteracciones',
            name='IDOportunidad',
        ),
        migrations.AddField(
            model_name='tblcrmoportunidades',
            name='SelectActividad',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tblcrmoportunidades',
            name='SelectAlimentacion',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tblcrmoportunidades',
            name='SelectDestino',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tblcrmoportunidades',
            name='SelectTipoGanado',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
