# Generated by Django 4.1.13 on 2026-03-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_remove_tblcrmbitacorainteracciones_idoportunidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcrmoportunidades',
            name='Volumen',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
