# Generated by Django 4.1.13 on 2026-03-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_tblcrmoportunidades_volumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcrmcontactos',
            name='Clave',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
