# Generated by Django 4.1.13 on 2026-03-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_tblcrmcontactos_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcrmvendedores',
            name='Clave',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
