# Generated by Django 4.1.13 on 2026-03-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0007_tblcrmvendedores_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcrmoportunidades',
            name='Clave',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
