# Generated by Django 4.1.13 on 2026-03-30 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0008_tblcrmoportunidades_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldetalleanimales',
            name='IDCorral',
        ),
        migrations.RemoveField(
            model_name='tblmovimientoanimales',
            name='IDCorral',
        ),
        migrations.AddField(
            model_name='tbldetallemovanimales',
            name='IDCorral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcorrales'),
        ),
    ]
